#!/usr/bin/env bash

os="$(awk -F= '/^ID=/ {print $2}' /etc/os-release)"
os="${os,,}"

cbuild() {
    mkdir -p "$(dirname "$1")"
    gcc -o "$1" -s -w "/nebulous/$(basename "$1")/main.c"
}

chownmod() {
    chown -R "$1" "$3"
    chmod -R "$2" "$3"
}

create_flag_account() {
    local i="$1"
    local pwd

    pwd="x"
    case "$2" in
        "passwd:"*) pwd="$(makepwd "${2#passwd:}")" ;;
    esac
    echo "flag$i:$pwd:12$i:12$i::/home/flag$i:/bin/bash" >>/etc/passwd

    pwd="!"
    case "$2" in
        "shadow:"*) pwd="${2#shadow:}" ;;
    esac
    genshadow "flag$i" "$pwd" >>/etc/shadow

    mkdir -p "/home/flag$i"
    touch "/home/flag$i/.hushlogin"

    chownmod "flag$i:nebulous" u=rwX,g=rX,o=- "/home/flag$i"
}

files_for() {
    rm -f -r "/home/nebulous/level$1"
    mkdir -p "/home/nebulous/level$1"
    mv "/nebulous/flag$1/hints.md" "/home/nebulous/level$1/"
    mv "/nebulous/flag$1/README.md" "/home/nebulous/level$1/"
}

genshadow() {
    local epoch="$(($(date +%s)/60/60/24))"

    case "$2" in
        "!") echo "$1:!:$epoch:0:99999:7:::" ;;
        *) echo "$1:$(makepwd "${2:-$1}"):$epoch:0:99999:7:::" ;;
    esac
}

gobuild() {
    mkdir -p "$(dirname "$1")"
    go build --buildvcs=false --ldflags="-s -w" -o "$1" --trimpath \
        "/nebulous/$(basename "$1")/main.go"
}

makepwd() {
    if makepasswd -h 2>/dev/null | grep -q -s "GNU"; then
        makepasswd --clearfrom=<(echo "$1") --crypt-md5 | \
            awk '{print $2}'
    else
        makepasswd -e sha256 -p "$1" | awk '{print $2}'
    fi
}

provide_src() {
    local ext="${2:-go}"

    mkdir -p "/home/flag$1/src"
    cp -f "/nebulous/flag$1/main.$ext" "/home/flag$1/src/flag$1.$ext"
    chownmod "flag$1:flag$1" u=rwX,go=rX "/home/flag$1/src"
}

suid() {
    chown "flag$1:nebulous" "$2"
    chmod u=srwx,go=rx "$2"
}

# Install deps
case "$os" in
    "alpine")
        apk --update upgrade
        apk add \
            curl \
            curl-doc \
            findutils \
            findutils-doc \
            go \
            iproute2 \
            iproute2-doc \
            john \
            makepasswd \
            man-pages \
            mandoc \
            nano \
            nmap-ncat \
            openssh \
            openssh-server-pam \
            patchelf \
            php \
            python3 \
            shadow \
            sshpass \
            strace \
            sudo \
            tmux \
            tshark \
            vim \
            wireshark-doc
        ;;
    "debian"|"ubuntu")
        case "$os" in
            "debian") rm -f /etc/dpkg/dpkg.cfg.d/docker &>/dev/null ;;
            "ubuntu")
                if [[ -z $(command -v unminimize) ]]; then
                    apt-get -q -y update
                    apt-get -q -y install unminimize
                fi

                yes | unminimize
                ;;
        esac

        apt-get -q -y update
        apt-get -q -y upgrade
        apt-get -q -y install man-db manpages
        apt-get -q -y reinstall \
            cron \
            curl \
            findutils \
            golang \
            iproute2 \
            iputils-ping \
            john \
            less \
            makepasswd \
            nano \
            ncat \
            openssh-server \
            patchelf \
            php \
            python3 \
            sshpass \
            strace \
            sudo \
            tmux \
            tshark \
            vim
        ;;
esac

# Accounts
echo "[*] Setting up accounts"
groupadd -f -g 1100 nebulous
for i in $(seq -w 0 19); do
    groupadd -f -g "12$i" "flag$i"
done; unset i
groupadd -f -g 2100 protostellar
groupadd -f -g 3100 fission

rm -f -r /root/* /root/.*
touch /root/.hushlogin

echo "nebulous:x:1100:1100::/home/nebulous:/bin/bash" >>/etc/passwd
genshadow nebulous >>/etc/shadow
mkdir -p /home/nebulous
touch /home/nebulous/.hushlogin

echo "protostellar:x:2100:2100::/home/protostellar:/bin/bash" \
    >>/etc/passwd
genshadow protostellar >>/etc/shadow
mkdir -p /home/protostellar
touch /home/protostellar/.hushlogin

echo "fission:x:3100:3100::/home/fission:/bin/bash" >>/etc/passwd
genshadow fission >>/etc/shadow
mkdir -p /home/fission
touch /home/fission/.hushlogin

# Aliases and whatnot
echo "[*] Creating shared /etc/profile"
cat >/etc/profile.d/99shared.sh <<EOF
alias la="\\ls -A --color=auto -F"
alias ls="\\ls --color=auto -F"
alias ll="\\ls --color=auto -F -h -l"
alias lla="\\ls -A --color=auto -F -h -l"
alias q="exit"

export GOPATH="\$HOME/.go"
export PS1="[\\u@\\h: \\w]\\n\$ "
export TERM="xterm"

# Standard PATH setup
PTH="\$HOME/bin:\$HOME/.local/bin:\$GOPATH/bin"
PTH="\$PTH:/usr/local/sbin:/usr/local/bin"
PTH="\$PTH:/usr/sbin:/usr/bin:/sbin:/bin"
export PATH="\$PTH"
EOF

# Password-less sudo
echo "[*] Configuring password-less sudo"
cat >/etc/sudoers.d/xploits <<EOF
fission ALL=(ALL:ALL) NOPASSWD: ALL
nebulous ALL=(ALL:ALL) NOPASSWD: ALL
protostellar ALL=(ALL:ALL) NOPASSWD: ALL
EOF
chmod u=r,go=- /etc/sudoers.d/xploits

# Main binary for all levels
echo "[*] Building getflag binary"
gobuild /bin/getflag
chmod u=rwx,go=rx /bin/getflag

# Fix /tmp permissions (docker-ism)
chmod -t /tmp

# Setting up all levels

## Nebulous

######################################################################
lvl="00"
echo "[*] Setting up level$lvl"
files_for "$lvl"
create_flag_account "$lvl"
gobuild "/bin/.../flag$lvl"
chownmod "flag$lvl:nebulous" u=srwx,go=rx "/bin/.../flag$lvl"

######################################################################
lvl="01"
echo "[*] Setting up level$lvl"
files_for "$lvl"
create_flag_account "$lvl"
provide_src "$lvl"
gobuild "/home/flag$lvl/flag$lvl"
chownmod "flag$lvl:nebulous" u=srwx,go=rx "/home/flag$lvl/flag$lvl"

######################################################################
lvl="02"
echo "[*] Setting up level$lvl"
files_for "$lvl"
create_flag_account "$lvl"
provide_src "$lvl"
gobuild "/home/flag$lvl/flag$lvl"
chownmod "flag$lvl:nebulous" u=srwx,go=rx "/home/flag$lvl/flag$lvl"

######################################################################
lvl="03"
echo "[*] Setting up level$lvl"
files_for "$lvl"
create_flag_account "$lvl"

mv "/nebulous/flag$lvl/writable.sh" "/home/flag$lvl/"
chownmod "flag$lvl:flag$lvl" u=rwx,go=rx "/home/flag$lvl/writable.sh"

mkdir -p "/home/flag$lvl/writable.d"
chownmod "flag$lvl:flag$lvl" ugo=rwx "/home/flag$lvl/writable.d"

mv "/nebulous/flag$lvl/crontab" "/var/spool/cron/crontabs/flag$lvl"
chownmod root:root u=rw,go=- "/var/spool/cron/crontabs/flag$lvl"

case "$os" in
    "alpine") crond ;;
    "debian"|"ubuntu") cron ;;
esac

######################################################################
lvl="04"
echo "[*] Setting up level$lvl"
files_for "$lvl"
flagpass="$(head -c 4 /dev/random | xxd -p)"
create_flag_account "$lvl" "shadow:$flagpass"
provide_src "$lvl"
gobuild "/home/flag$lvl/flag$lvl"
chownmod "flag$lvl:nebulous" u=srwx,go=rx "/home/flag$lvl/flag$lvl"

echo "flag$lvl's password is $flagpass" >"/home/flag$lvl/passwd.txt"
chownmod "flag$lvl:flag$lvl" u=rw,go=- "/home/flag$lvl/passwd.txt"

######################################################################
lvl="05"
echo "[*] Setting up level$lvl"
files_for "$lvl"
create_flag_account "$lvl"

mkdir -p "/home/flag$lvl/.ssh"
ssh-keygen -f "/home/flag$lvl/.ssh/id_ed25519" -N "" -q -t ed25519
mv "/home/flag$lvl/.ssh/id_ed25519.pub" \
    "/home/flag$lvl/.ssh/authorized_keys"
chownmod "flag$lvl:flag$lvl" u=rwX,go=- "/home/flag$lvl/.ssh"

tgz="backup-$(date +%Y%m%d).tgz"
mkdir -p "/home/flag$lvl/.backup"
tar -C "/home/flag$lvl" -c -f "/home/flag$lvl/.backup/$tgz" -z ./.ssh
chownmod "flag$lvl:flag$lvl" u=rwX,go=rX "/home/flag$lvl/.backup"

######################################################################
lvl="06"
echo "[*] Setting up level$lvl"
files_for "$lvl"
flagpass="$(shuf /usr/share/john/password.lst | head -n 1)"
create_flag_account "$lvl" "passwd:$flagpass"

######################################################################
lvl="07"
echo "[*] Setting up level$lvl"
files_for "$lvl"
create_flag_account "$lvl"
provide_src "$lvl"
gobuild "/home/flag$lvl/flag$lvl"
chownmod "flag$lvl:flag$lvl" u=rwx,go=- "/home/flag$lvl/flag$lvl"

sudo -u "flag$lvl" "/home/flag$lvl/flag$lvl" &

######################################################################
lvl="08"
echo "[*] Setting up level$lvl"
files_for "$lvl"
create_flag_account "$lvl" "shadow:backd00Rmate" # Password from pcap

# FIXME can I programmatically create this?
mv "/nebulous/flag$lvl/capture.pcap" "/home/flag$lvl/"
chownmod "flag$lvl:flag$lvl" u=rw,go=r "/home/flag$lvl/capture.pcap"

######################################################################
lvl="09"
echo "[*] Setting up level$lvl"
files_for "$lvl"
create_flag_account "$lvl"
gobuild "/home/flag$lvl/flag$lvl"
chownmod "flag$lvl:nebulous" u=srwx,go=rx "/home/flag$lvl/flag$lvl"

# Real version with simulated vulnerability
mv "/nebulous/flag$lvl/simulated.php" "home/flag$lvl/.flag$lvl.php"
chownmod "flag$lvl:flag$lvl" u=rw,go=- "/home/flag$lvl/.flag$lvl.php"

# Original version for user to discover vulnerability
mv "/nebulous/flag$lvl/original.php" "home/flag$lvl/flag$lvl.php"
chownmod "flag$lvl:flag$lvl" u=rw,go=r "/home/flag$lvl/flag$lvl.php"

######################################################################
lvl="10"
echo "[*] Setting up level$lvl"
files_for "$lvl"
flagpass="$(head -c 4 /dev/random | xxd -p)"
create_flag_account "$lvl" "shadow:$flagpass"
provide_src "$lvl"
gobuild "/home/flag$lvl/flag$lvl"
chownmod "flag$lvl:nebulous" u=srwx,go=rx "/home/flag$lvl/flag$lvl"

echo "flag$lvl's password is $flagpass" >"/home/flag$lvl/passwd.txt"
chownmod "flag$lvl:flag$lvl" u=rw,go=- "/home/flag$lvl/passwd.txt"

######################################################################
lvl="11"
echo "[*] Setting up level$lvl"
files_for "$lvl"
create_flag_account "$lvl"
provide_src "$lvl"
gobuild "/home/flag$lvl/flag$lvl"
chownmod "flag$lvl:nebulous" u=srwx,go=rx "/home/flag$lvl/flag$lvl"

mkdir -p "/home/flag$lvl/.ssh"
chownmod "flag$lvl:flag$lvl" u=rwx,go=rx "/home/flag$lvl/.ssh"

######################################################################
lvl="12"
echo "[*] Setting up level$lvl"
files_for "$lvl"
create_flag_account "$lvl"
provide_src "$lvl"
gobuild "/home/flag$lvl/flag$lvl"
chownmod "flag$lvl:flag$lvl" u=rwx,go=- "/home/flag$lvl/flag$lvl"

sudo -u "flag$lvl" "/home/flag$lvl/flag$lvl" &

######################################################################
lvl="13"
echo "[*] Setting up level$lvl"
files_for "$lvl"
flagpass="$(head -c 4 /dev/random | xxd -p)"
create_flag_account "$lvl" "shadow:$flagpass"
provide_src "$lvl"
sed -i "s/FLAGPASS/flag$lvl's password is $flagpass/" \
    "/nebulous/flag$lvl/main.go"
gobuild "/home/flag$lvl/flag$lvl"
chownmod "flag$lvl:nebulous" u=srwx,go=rx "/home/flag$lvl/flag$lvl"

######################################################################
lvl="14"
echo "[*] Setting up level$lvl"
files_for "$lvl"
flagpass="$(head -c 4 /dev/random | xxd -p)"
create_flag_account "$lvl" "shadow:$flagpass"

go run "/nebulous/flag$lvl/main.go" >"/home/flag$lvl/passwd.txt" <<EOF
flag$lvl's password is $flagpass
EOF
chownmod "flag$lvl:flag$lvl" u=rw,go=r "/home/flag$lvl/passwd.txt"

gobuild "/home/flag$lvl/flag$lvl"
chownmod "flag$lvl:nebulous" u=srwx,go=rx "/home/flag$lvl/flag$lvl"

######################################################################
lvl="15"
# echo "[*] Setting up level$lvl"
# TODO flag15

######################################################################
lvl="16"
echo "[*] Setting up level$lvl"
files_for "$lvl"
create_flag_account "$lvl"
gobuild "/home/flag$lvl/flag$lvl"
chownmod "flag$lvl:nebulous" u=rwx,go=- "/home/flag$lvl/flag$lvl"
touch "/home/flag$lvl/userdb.txt"
chownmod "flag$lvl:flag$lvl" u=rw,go=- "/home/flag$lvl/userdb.txt"

sudo -u "flag$lvl" "/home/flag$lvl/flag$lvl" &

######################################################################
lvl="17"
echo "[*] Setting up level$lvl"
files_for "$lvl"
create_flag_account "$lvl"

mv "/nebulous/flag$lvl/main.py" "home/flag$lvl/flag$lvl.py"
chownmod "flag$lvl:flag$lvl" u=rwx,go=r "/home/flag$lvl/flag$lvl.py"

sudo -u "flag$lvl" "/home/flag$lvl/flag$lvl.py" &

######################################################################
lvl="18"
# echo "[*] Setting up level$lvl"
# TODO flag18

######################################################################
lvl="19"
echo "[*] Setting up level$lvl"
files_for "$lvl"
create_flag_account "$lvl"
provide_src "$lvl"
gobuild "/home/flag$lvl/flag$lvl"
chownmod "flag$lvl:nebulous" u=srwx,go=rx "/home/flag$lvl/flag$lvl"

## Protostellar
# TODO protosteller

## Fission
# TODO fission

# Unit tests
if [[ "$TESTS" == "true" ]]; then
    mv /nebulous/tests /.unit-tests
    chownmod nebulous:nebulous u=rwx,go=- /.unit-tests
fi

# No more levels
unset lvl
chownmod nebulous:nebulous u=rwX,go=- /home/nebulous
chownmod protostellar:protostellar u=rwX,go=- /home/protostellar
chownmod fission:fission u=rwX,go=- /home/fission
rm -f -r /nebulous

# No motd
echo -n >/etc/motd

# Configure SSH
echo "[*] Setting up /etc/ssh/sshd_config"
cat << EOF | tee /etc/ssh/sshd_config
PasswordAuthentication yes
PermitEmptyPasswords no
PermitRootLogin yes
Port 22
PrintMotd no
PubkeyAuthentication yes
UsePAM yes
EOF

# Create host keys, if needed
mkdir -p /etc/ssh
ssh-keygen -A

# SSH
if [[ -f /usr/sbin/sshd.pam ]]; then
    /usr/sbin/sshd.pam -D -e
elif [[ -f /usr/sbin/sshd ]]; then
    mkdir -p /run/sshd
    /usr/sbin/sshd -D -e
fi
